export const productData = [
  {
    img: "/images/searm3.png",
    title: "Semaglutide Consultation",
    price: "$199",
    type: "Appointment Only",
    features: [
      "Online medical visit with provider",
      "Evaluation for GLP-1 therapy suitability",
      "Prescription if appropriate",
      "Medication not included",
      "Provider answers your questions",
      "Follow-ups not included",
      "One time consult",
    ],
  },
  {
    img: "/images/serum.png",
    title: "Tirzepatide Consultation",
    price: "$199",
    type: "Appointment Only",
    features: [
      "Online medical visit with provider",
      "Evaluation for GLP-1 therapy suitability",
      "Prescription if appropriate",
      "Medication not included",
      "Provider answers your questions",
      "Follow-ups not included",
      "One time consult",
    ],
  },
  {
    img: "/images/searm1.png",
    title: "Semaglutide Package",
    price: "$399",
    type: "Medication + Appointment",
    features: [
      "Online medical visit with provider",
      "Evaluation for GLP-1 therapy suitability",
      "Prescription if appropriate",
      "Provider answers your questions",
      "Follow-ups included",
      "Medication included (1 month)",
      "No insurance required",
    ],
  },
  {
    img: "/images/searm2.png",
    title: "Tirzepatide Package",
    price: "$499",
    type: "Medication + Appointment",
    features: [
      "Online medical visit with provider",
      "Evaluation for GLP-1 therapy suitability",
      "Prescription if appropriate",
      "Provider answers your questions",
      "Follow-ups included",
      "Medication included (1 month)",
      "Cash Pay, No insurance required",
    ],
  },
];
